#!/usr/bin/env bash
set -euo pipefail

START_MODE="ask"
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
PandaWiki 生产环境交互式初始化脚本

用法：
  bash scripts/setup_production.sh
  bash scripts/setup_production.sh --start
  bash scripts/setup_production.sh --no-start

功能：
  1. 交互式设置生产密码/密钥
  2. 生成 deploy/production/.env
  3. 如 .env 已存在，自动备份
  4. 可选择执行 docker compose up -d --build

注意：
  - .env 会保存明文密码，Docker Compose 需要读取；请妥善保护服务器文件权限。
  - 为兼容 docker-compose v1/v2，密码仅允许安全字符：
    A-Z a-z 0-9 . _ ~ ! @ % + = : , / -
EOF
  exit 0
elif [[ "${1:-}" == "--start" ]]; then
  START_MODE="start"
elif [[ "${1:-}" == "--no-start" ]]; then
  START_MODE="no-start"
elif [[ -n "${1:-}" ]]; then
  echo "未知参数：$1" >&2
  exit 2
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_DIR="$ROOT_DIR/deploy/production"
ENV_PATH="$DEPLOY_DIR/.env"

if [[ ! -f "$DEPLOY_DIR/docker-compose.yml" ]]; then
  echo "未找到 deploy/production/docker-compose.yml，请确认在完整项目目录中执行。" >&2
  exit 1
fi

safe_re='^[A-Za-z0-9._~!@%+=:,/-]+$'

generate_secret() {
  local length="${1:-48}"
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$length" <<'PY'
import secrets
import sys
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._~!@%+=:,/-"
length = int(sys.argv[1])
print("".join(secrets.choice(alphabet) for _ in range(length)))
PY
  else
    LC_ALL=C tr -dc 'A-Za-z0-9._~!@%+=:,/-' </dev/urandom | head -c "$length"
    echo
  fi
}

read_hidden() {
  local prompt="$1"
  local value
  read -r -s -p "$prompt" value
  echo >&2
  printf '%s' "$value"
}

read_required_secret() {
  local name="$1"
  local min_len="$2"
  local value1 value2
  while true; do
    value1="$(read_hidden "请输入 $name：")"
    if [[ -z "$value1" ]]; then
      echo "不能为空，请重新输入。" >&2
      continue
    fi
    if (( ${#value1} < min_len )); then
      echo "长度至少 $min_len 位，请重新输入。" >&2
      continue
    fi
    if [[ ! "$value1" =~ $safe_re ]]; then
      echo "包含不兼容字符。仅允许 A-Z a-z 0-9 . _ ~ ! @ % + = : , / -" >&2
      continue
    fi
    value2="$(read_hidden "请再次输入 $name：")"
    if [[ "$value1" != "$value2" ]]; then
      echo "两次输入不一致，请重新输入。" >&2
      continue
    fi
    printf '%s' "$value1"
    return 0
  done
}

read_optional_secret() {
  local name="$1"
  local min_len="$2"
  local gen_len="$3"
  local value1 value2
  while true; do
    value1="$(read_hidden "请输入 $name（直接回车则自动生成）：")"
    if [[ -z "$value1" ]]; then
      generate_secret "$gen_len"
      return 0
    fi
    if (( ${#value1} < min_len )); then
      echo "长度至少 $min_len 位，请重新输入；或直接回车自动生成。" >&2
      continue
    fi
    if [[ ! "$value1" =~ $safe_re ]]; then
      echo "包含不兼容字符。仅允许 A-Z a-z 0-9 . _ ~ ! @ % + = : , / -" >&2
      continue
    fi
    value2="$(read_hidden "请再次输入 $name：")"
    if [[ "$value1" != "$value2" ]]; then
      echo "两次输入不一致，请重新输入。" >&2
      continue
    fi
    printf '%s' "$value1"
    return 0
  done
}

find_compose() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "未检测到 docker，请先安装 Docker Engine。" >&2
    return 1
  fi
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
    return 0
  fi
  if command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
    return 0
  fi
  echo "未检测到 docker compose 或 docker-compose，请先安装 Docker Compose。" >&2
  return 1
}

echo "PandaWiki 生产环境初始化"
echo "项目目录：$ROOT_DIR"
echo
echo "请设置以下生产密码。输入过程不会显示明文。"
echo

ADMIN_PASSWORD="$(read_required_secret "后台 admin 密码 ADMIN_PASSWORD" 12)"
POSTGRES_PASSWORD="$(read_required_secret "PostgreSQL 密码 POSTGRES_PASSWORD" 16)"
NATS_PASSWORD="$(read_required_secret "NATS 密码 NATS_PASSWORD" 16)"
S3_SECRET_KEY="$(read_required_secret "MinIO/S3 密码 S3_SECRET_KEY/MINIO_ROOT_PASSWORD" 16)"
QDRANT_API_KEY="$(read_required_secret "Qdrant API Key QDRANT_API_KEY" 16)"
JWT_SECRET="$(read_optional_secret "JWT_SECRET" 32 64)"

if [[ -f "$ENV_PATH" ]]; then
  BACKUP_PATH="$ENV_PATH.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$ENV_PATH" "$BACKUP_PATH"
  echo "已备份原 .env：$BACKUP_PATH"
fi

cat >"$ENV_PATH" <<EOF
# Generated by scripts/setup_production.sh at $(date '+%Y-%m-%d %H:%M:%S %z')
# Do not commit this file. It contains production secrets.

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
NATS_PASSWORD=$NATS_PASSWORD
QDRANT_API_KEY=$QDRANT_API_KEY
JWT_SECRET=$JWT_SECRET

# MinIO root user must stay aligned with compose service defaults used by API/RAGLite/Crawler.
MINIO_ROOT_USER=s3panda-wiki
MINIO_ROOT_PASSWORD=$S3_SECRET_KEY
S3_SECRET_KEY=$S3_SECRET_KEY

ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF

chmod 600 "$ENV_PATH" || true

echo
echo "已生成生产配置：$ENV_PATH"

if ! COMPOSE_CMD="$(find_compose)"; then
  echo "配置文件已生成；安装 Docker/Compose 后可手动执行：cd deploy/production && docker compose up -d --build" >&2
  exit 1
fi
echo "Docker Compose：$COMPOSE_CMD"

SHOULD_START="false"
case "$START_MODE" in
  start)
    SHOULD_START="true"
    ;;
  no-start)
    SHOULD_START="false"
    ;;
  ask)
    read -r -p "是否现在构建并启动生产服务？输入 y 启动，其他键跳过：" answer
    if [[ "$answer" =~ ^([yY]|yes|YES)$ ]]; then
      SHOULD_START="true"
    fi
    ;;
esac

if [[ "$SHOULD_START" == "true" ]]; then
  echo "开始构建并启动生产服务..."
  (cd "$DEPLOY_DIR" && $COMPOSE_CMD up -d --build)
  echo
  echo "服务状态："
  (cd "$DEPLOY_DIR" && $COMPOSE_CMD ps)
  echo
  echo "后台入口：https://服务器IP:2443/login"
  echo "后台账号：admin"
  echo "后台密码：你刚才交互输入的 ADMIN_PASSWORD"
else
  echo
  echo "已跳过启动。后续可执行："
  echo "  cd deploy/production"
  echo "  docker compose up -d --build"
fi
